[build]
  command = "rm -rf node_modules && npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  SECRETS_SCAN_OMIT_KEYS = "VITE_GOOGLE_API_KEY,VITE_GOOGLE_CLIENT_ID"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' https://cdn.jsdelivr.net https://apis.google.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com data:;
      img-src 'self' data: blob:;
      connect-src 'self' https://*.supabase.co https://generativelanguage.googleapis.com https://www.googleapis.com https://accounts.google.com;
      frame-ancestors 'none';
      base-uri 'self';
      object-src 'none';
    """

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
